import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { Smartphone, Download, CheckCircle2, ShieldCheck, Zap, X, Play, Share2, Apple } from 'lucide-react';

interface MobileInstallModalProps { onClose: () => void; deferredPrompt?: any; }

export default function MobileInstallModal({ onClose, deferredPrompt }: MobileInstallModalProps) {
  const [isInstalling, setIsInstalling] = useState(false);
  const [installSuccess, setInstallSuccess] = useState(false);
  const [activeTab, setActiveTab] = useState<'android' | 'ios'>('android');
  useEffect(() => { const isIos = /ipad|iphone|ipod/.test(navigator.userAgent.toLowerCase()) && !(window as any).MSStream; if (isIos) setActiveTab('ios'); }, [deferredPrompt]);
  const handleInstallClick = async () => {
    if (deferredPrompt) { setIsInstalling(true); deferredPrompt.prompt(); const { outcome } = await deferredPrompt.userChoice; if (outcome === 'accepted') setInstallSuccess(true); setIsInstalling(false); }
    else alert("Para instalar no Android: abra o menu do navegador e toque em 'Instalar aplicativo' ou 'Adicionar à tela inicial'.");
  };
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md overflow-y-auto" id="mobile-install-modal">
      <motion.div initial={{ opacity: 0, scale: 0.95, y: 15 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: 0.95, y: 15 }} className="w-full max-w-lg bg-slate-900 border border-slate-800 rounded-3xl p-6 md:p-8 shadow-2xl space-y-6 relative overflow-hidden my-4">
        <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" /><div className="absolute bottom-0 left-0 w-64 h-64 bg-amber-500/10 rounded-full blur-3xl pointer-events-none" />
        <button onClick={onClose} aria-label="Fechar" className="absolute top-5 right-5 p-2 text-slate-400 hover:text-white rounded-full bg-slate-800/60 hover:bg-slate-800 transition cursor-pointer border-none z-10"><X size={18} /></button>
        <div className="flex items-center gap-3.5 relative z-10"><div className="w-14 h-14 bg-emerald-500/10 border border-emerald-500/30 rounded-2xl flex items-center justify-center text-emerald-400 shrink-0"><Smartphone size={28} /></div><div><span className="text-[10px] font-mono font-bold text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2.5 py-0.5 rounded-full uppercase tracking-wider">App Oficial</span><h3 className="text-lg md:text-xl font-display font-medium text-slate-100 mt-1">Instalar no celular</h3></div></div>
        <div className="flex bg-slate-950 rounded-xl p-1 relative z-10"><button onClick={() => setActiveTab('android')} className={`flex-1 flex items-center justify-center gap-2 py-2 text-xs font-semibold rounded-lg border-none cursor-pointer ${activeTab === 'android' ? 'bg-emerald-500/20 text-emerald-400' : 'text-slate-400 bg-transparent'}`}><Play size={14} /> Android</button><button onClick={() => setActiveTab('ios')} className={`flex-1 flex items-center justify-center gap-2 py-2 text-xs font-semibold rounded-lg border-none cursor-pointer ${activeTab === 'ios' ? 'bg-amber-500/20 text-amber-300' : 'text-slate-400 bg-transparent'}`}><Apple size={14} /> iOS</button></div>
        <div className="p-4 rounded-2xl bg-slate-950/80 border border-slate-800 flex items-center gap-4 relative z-10"><div className="w-14 h-14 rounded-2xl overflow-hidden bg-slate-900 border border-slate-800 flex items-center justify-center shrink-0"><img src="/icon-192.svg" alt="Ícone do aplicativo" className="w-12 h-12 object-contain" /></div><div className="min-w-0 flex-1"><h4 className="text-sm font-semibold text-slate-200 truncate">Protocolo da Transformação</h4><p className="text-xs text-slate-400 truncate">Por Éverton Rodrigo Piceni</p><p className="mt-1 text-[11px] text-emerald-400">Um lugar para voltar para si.</p></div></div>
        {activeTab === 'android' ? <div className="space-y-4 relative z-10"><div className="space-y-2.5 text-xs"><div className="flex items-start gap-3 p-2.5 rounded-xl bg-slate-950/40 border border-slate-800/60 text-slate-300"><ShieldCheck size={16} className="text-emerald-400 shrink-0 mt-0.5" /><div><strong className="text-slate-100 block">Acesso pela tela inicial</strong>Use o projeto como aplicativo em tela cheia no seu celular.</div></div><div className="flex items-start gap-3 p-2.5 rounded-xl bg-slate-950/40 border border-slate-800/60 text-slate-300"><Zap size={16} className="text-amber-400 shrink-0 mt-0.5" /><div><strong className="text-slate-100 block">Seu espaço de cuidado por perto</strong>Acesse seus momentos, jornadas e recursos com facilidade.</div></div></div>{installSuccess ? <div className="p-3 bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 rounded-xl text-center text-xs font-medium">Aplicativo instalado. Verifique a tela inicial.</div> : <button onClick={handleInstallClick} disabled={isInstalling} className="w-full bg-gradient-to-r from-emerald-700 to-amber-500 text-white font-medium py-3.5 rounded-xl text-xs tracking-wider uppercase flex items-center justify-center gap-2 border-none"><Download size={16} />{isInstalling ? 'Instalando...' : 'Instalar no Android'}</button>}</div> : <div className="relative z-10 p-4 rounded-xl bg-slate-950/40 border border-slate-800/60 text-sm text-slate-300 space-y-4"><p className="font-medium text-slate-200 text-xs">No Safari:</p><ol className="space-y-4 list-decimal pl-5 text-xs"><li className="pl-2">Toque em <strong className="text-white">Compartilhar</strong>.<div className="mt-2 flex justify-center"><Share2 size={20} /></div></li><li className="pl-2">Selecione <strong className="text-white">Adicionar à Tela de Início</strong>.</li><li className="pl-2">Confirme em <strong className="text-white">Adicionar</strong>.</li></ol><div className="p-3 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-xs text-emerald-300 flex gap-2"><CheckCircle2 size={16} className="shrink-0" /><p>Depois disso, o Protocolo da Transformação ficará disponível na sua tela inicial.</p></div></div>}
      </motion.div>
    </div>
  );
}
