import React,{useEffect,useRef,useState}from'react';
import{ArrowLeft,Check,ChevronLeft,ChevronRight,Headphones,Pause,Play,RotateCcw,ShieldCheck,X}from'lucide-react';
import{REINTEGRATION_DAYS}from'../data/reintegrationJourneyPublic';
import{REINTEGRATION_DAY_DETAILS,acceptanceForDay}from'../data/reintegrationDayDetails';
type Props={onClose:()=>void};
const STORAGE_KEY='transformacao_jornada_pessoal_21_dias_v1';
const MUSIC='https://7bhxppl2irhgbptb.public.blob.vercel-storage.com/REINTEGRA%C3%87%C3%83O%20%C3%80%20VIDA.mp3';
const CHAKRAS=[{name:'Coronário (Sahasrara)',color:'#a855f7',top:'22%'},{name:'Frontal (Ajna)',color:'#6366f1',top:'31%'},{name:'Laríngeo (Vishuddha)',color:'#38bdf8',top:'40%'},{name:'Cardíaco (Anahata)',color:'#22c55e',top:'50%'},{name:'Plexo Solar (Manipura)',color:'#eab308',top:'60%'},{name:'Sacral (Svadhisthana)',color:'#f97316',top:'69%'},{name:'Básico (Muladhara)',color:'#ef4444',top:'78%'}]as const;
export default function PersonalJourney21({onClose}:Props){
 const[day,setDay]=useState(1),[accepted,setAccepted]=useState(false),[playing,setPlaying]=useState(false),[started,setStarted]=useState(false),[progress,setProgress]=useState(0);
 const[completed,setCompleted]=useState<number[]>(()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}});
 const music=useRef<HTMLAudioElement|null>(null),voice=useRef<HTMLAudioElement|null>(null),voiceUrl=useRef<string|null>(null),lastCue=useRef(-1),pending=useRef(false),playingRef=useRef(false),sessionStart=useRef(0),sessionOffset=useRef(0);
 const item=REINTEGRATION_DAYS[day-1],detail=REINTEGRATION_DAY_DETAILS[day-1],elapsed=music.current?.currentTime||0,total=music.current?.duration||1797,life=Math.max(0,Math.min(1,progress/100));
 const active=(name:string)=>detail.chakras.includes(name)||detail.chakras.includes('Chakras celestiais');
 const fmt=(s:number)=>`${Math.floor(s/60)}:${Math.floor(s%60).toString().padStart(2,'0')}`;
 const reflection=elapsed<240?'O que o seu corpo precisa para se sentir seguro neste momento?':elapsed<360?item.intention:elapsed<660?item.reflectionPrompts[0]:elapsed<900?item.reflectionPrompts[1]:elapsed<1260?'Onde você percebe essas energias e sensações atuando no seu corpo agora?':elapsed<1620?'Respire naturalmente. Não procure respostas. Apenas permita a integração.':'Que pequeno movimento desta prática você deseja levar para o seu dia?';
 const clearVoice=()=>{if(voice.current){voice.current.pause();voice.current.src='';voice.current=null}if(voiceUrl.current){URL.revokeObjectURL(voiceUrl.current);voiceUrl.current=null}pending.current=false};
 const stop=()=>{playingRef.current=false;clearVoice();music.current?.pause();setPlaying(false)};
 const syncClock=()=>{const a=music.current;if(!a||!playingRef.current)return a?.currentTime||0;const expected=sessionOffset.current+(performance.now()-sessionStart.current)/1000;if(Math.abs(a.currentTime-expected)>2&&Number.isFinite(expected))a.currentTime=Math.min(expected,a.duration||expected);return a.currentTime};
 const cue=async(t:number)=>{if(!playingRef.current||pending.current||(voice.current&&!voice.current.paused))return;const i=item.audioCues.reduce((n,c,k)=>c.at<=t+.5?k:n,-1);if(i<0||i<=lastCue.current)return;const c=item.audioCues[i];if(t-c.at>12){lastCue.current=i;return}pending.current=true;try{const r=await fetch('/api/reintegration-tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:c.text,day})});if(!r.ok||!r.headers.get('content-type')?.includes('audio'))throw new Error(String(r.status));const b=await r.blob();if(!playingRef.current)return;const u=URL.createObjectURL(b);voiceUrl.current=u;const a=new Audio(u);a.preload='auto';voice.current=a;a.onended=()=>{voice.current=null;URL.revokeObjectURL(u);voiceUrl.current=null;pending.current=false;void cue(syncClock())};a.onerror=()=>{pending.current=false};await a.play();lastCue.current=i}catch(e){console.warn('Reintegração: voz indisponível',e);pending.current=false}};
 useEffect(()=>()=>stop(),[]);
 useEffect(()=>{stop();setAccepted(false);setStarted(false);setProgress(0);lastCue.current=-1;if(music.current)music.current.currentTime=0},[day]);
 useEffect(()=>{playingRef.current=playing},[playing]);
 useEffect(()=>{const recover=()=>{if(!playingRef.current)return;const a=music.current;if(!a)return;const t=syncClock();if(a.paused)void a.play().catch(()=>undefined);if(voice.current?.paused&&voice.current.currentTime>0)void voice.current.play().catch(()=>undefined);void cue(t)};document.addEventListener('visibilitychange',recover);window.addEventListener('pageshow',recover);window.addEventListener('focus',recover);return()=>{document.removeEventListener('visibilitychange',recover);window.removeEventListener('pageshow',recover);window.removeEventListener('focus',recover)}},[day]);
 useEffect(()=>{const ms=(navigator as any).mediaSession;if(!ms)return;ms.metadata=new MediaMetadata({title:`Dia ${day}: ${item.title}`,artist:'Reintegração da Vida',album:'21 Dias para Voltar para Mim'});const action=(name:string,fn:()=>void)=>{try{ms.setActionHandler(name,fn)}catch{}};action('play',()=>{if(!playingRef.current)void toggle()});action('pause',()=>{if(playingRef.current)void toggle()});action('seekbackward',()=>rewind());return()=>{for(const name of['play','pause','seekbackward'])try{ms.setActionHandler(name,null)}catch{}}},[day,accepted,playing]);
 const toggle=async()=>{if(!accepted)return;if(playing){sessionOffset.current=music.current?.currentTime||sessionOffset.current;voice.current?.pause();music.current?.pause();playingRef.current=false;setPlaying(false);return}setStarted(true);if(progress>=99&&music.current){music.current.currentTime=0;setProgress(0);lastCue.current=-1}sessionOffset.current=music.current?.currentTime||0;sessionStart.current=performance.now();playingRef.current=true;setPlaying(true);await music.current?.play().catch(()=>undefined);if(voice.current?.paused)await voice.current.play().catch(()=>undefined);void cue(music.current?.currentTime||0)};
 const rewind=()=>{if(!music.current)return;clearVoice();music.current.currentTime=Math.max(0,music.current.currentTime-15);sessionOffset.current=music.current.currentTime;sessionStart.current=performance.now();lastCue.current=item.audioCues.reduce((n,c,k)=>c.at<music.current!.currentTime?k:n,-1);void cue(music.current.currentTime)};
 const complete=()=>{stop();const n=completed.includes(day)?completed:[...completed,day].sort((a,b)=>a-b);setCompleted(n);localStorage.setItem(STORAGE_KEY,JSON.stringify(n));if(day<21)setDay(day+1)};
 const Lights=({large=false}:{large?:boolean})=><>{CHAKRAS.map(ch=>{const on=active(ch.name),g=on?Math.max(.18,life):0;return <span key={ch.name} className={`absolute left-1/2 -translate-x-1/2 rounded-full border transition-all duration-[2200ms] ${large?'h-7 w-7':'h-5 w-5'} ${playing&&on?'animate-pulse':''}`} style={{top:ch.top,backgroundColor:ch.color,opacity:on?.28+g*.72:.08,transform:`translateX(-50%) scale(${on?.78+g*.5:.62})`,boxShadow:on?`0 0 ${8+g*34}px ${2+g*12}px ${ch.color}`:'none',borderColor:on?'rgba(255,255,255,.8)':'rgba(255,255,255,.2)'}}/>})}</>;
 return <div className="min-h-screen bg-[#9fbaa2] px-4 py-5 text-[#173f35]">
  <audio ref={music} src={MUSIC} preload="auto" playsInline onTimeUpdate={e=>{const a=e.currentTarget;if(a.duration)setProgress(a.currentTime/a.duration*100);void cue(a.currentTime)}} onPlay={()=>{if(playingRef.current){sessionOffset.current=music.current?.currentTime||0;sessionStart.current=performance.now()}}} onEnded={()=>{clearVoice();playingRef.current=false;setPlaying(false);setProgress(100)}}/>
  <main className="mx-auto w-full max-w-[620px]"><button onClick={()=>{stop();onClose()}} className="mb-4 flex items-center gap-2 rounded-full bg-[#fffaf0]/90 px-4 py-2 text-sm font-semibold"><ArrowLeft size={17}/>Voltar ao início</button><section className="overflow-hidden rounded-[2rem] border border-[#d6ae52]/40 bg-[#fffaf0]/95 shadow-xl">
   <header className="bg-gradient-to-br from-[#315f49] to-[#244c3a] px-6 py-7 text-[#fffaf0]"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#ead28d]">21 Dias para Voltar para Mim</p><p className="mt-2 font-display text-xl italic">Reintegração da Vida</p><h1 className="mt-3 font-display text-3xl">Dia {day}: {item.title}</h1><p className="mt-3">{item.cycle}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-black/20"><div className="h-full bg-[#d6ae52]" style={{width:`${completed.length/21*100}%`}}/></div><p className="mt-2 text-xs">{completed.length} de 21 momentos concluídos</p></header>
   <div className="space-y-5 p-5 sm:p-6"><div className="grid grid-cols-7 gap-2">{REINTEGRATION_DAYS.map(d=><button key={d.day} onClick={()=>setDay(d.day)} className={`flex aspect-square items-center justify-center rounded-full border text-xs font-bold ${day===d.day?'bg-[#315f49] text-white':completed.includes(d.day)?'bg-[#ead28d]':'bg-[#e7eee5]'}`}>{completed.includes(d.day)?<Check size={14}/>:d.day}</button>)}</div>
    <article className="rounded-3xl bg-[#e7eee5]/70 p-5"><p className="text-xs uppercase tracking-[.16em] text-[#587d67]">Intenção do dia</p><p className="mt-2 leading-7">{item.intention}</p></article>
    <article className="rounded-3xl border border-[#d6ae52]/35 bg-[#fff7df] p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#9a742b]">Chakras trabalhados hoje</p><div className="mt-3 flex flex-wrap gap-2">{detail.chakras.map(c=><span key={c} className="rounded-full bg-[#e7eee5] px-3 py-1.5 text-xs font-semibold">{c}</span>)}</div><p className="mt-4 text-sm leading-6 text-[#587d67]">{detail.chakraExplanation}</p></article>
    <section className="relative h-[500px] overflow-hidden rounded-[2rem] bg-[#173f35]"><img src="/brand/human-chakra-model.jpg" alt="Corpo em meditação com chakras do dia" className="absolute inset-0 h-full w-full object-cover object-top" style={{filter:`brightness(${.58+life*.42})`}}/><div className="absolute inset-0 bg-gradient-to-t from-[#173f35] via-transparent to-[#173f35]/25"/><Lights/><div className="absolute inset-x-4 bottom-4 rounded-2xl bg-white/75 p-4 text-center"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#9a742b]">{playing?'Meditação guiada em andamento':'Sua meditação guiada'}</p><p className="mt-2 text-sm text-[#587d67]">{playing?'Os chakras deste dia se iluminam conforme a prática avança.':'Voz feminina, música e experiência visual ligada ao propósito de hoje.'}</p></div></section>
    <label className="flex cursor-pointer items-start gap-3 rounded-3xl border border-[#d6ae52]/35 bg-[#fff7df] p-5"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} className="mt-1 h-5 w-5 accent-[#315f49]"/><span className="text-sm leading-6"><b className="mb-2 block">Aceite do Dia {day}</b>{acceptanceForDay(day,item.title)}</span></label>
    <button disabled={!accepted} onClick={toggle} className="flex w-full items-center justify-center gap-3 rounded-2xl bg-gradient-to-r from-[#efd78f] to-[#d4aa4e] px-5 py-4 font-bold disabled:opacity-40">{playing?<Pause size={20}/>:started?<Play size={20}/>:<Headphones size={20}/>} {playing?'Pausar meditação':started?'Continuar meditação':'Iniciar meditação guiada'}</button>
    <article className="rounded-3xl bg-[#e7eee5]/55 p-5"><p className="text-xs uppercase tracking-[.16em] text-[#587d67]">Programação energética deste dia</p><p className="mt-3 text-sm leading-6 text-[#587d67]">{detail.integration}</p>{item.energyNotes.map(n=><div key={n.name} className="mt-3 rounded-2xl bg-[#fffaf0] p-4"><strong className="text-sm">{n.name}</strong><p className="mt-2 text-sm leading-6 text-[#587d67]"><b>Atuação:</b> {n.focus}</p></div>)}</article>
    <p className="flex gap-2 text-xs leading-5 text-[#587d67]"><ShieldCheck size={17}/>Experiência espiritual e integrativa complementar; não substitui atendimento médico, psicológico ou apoio humano necessário.</p>
    <div className="flex items-center justify-between border-t pt-5"><button disabled={day===1} onClick={()=>setDay(day-1)} className="flex items-center text-sm font-semibold disabled:opacity-30"><ChevronLeft size={18}/>Anterior</button><button onClick={complete} className="rounded-full bg-[#315f49] px-5 py-3 text-sm font-bold text-white">{day===21?'Concluir jornada':'Concluir dia'}</button><button disabled={day===21} onClick={()=>setDay(day+1)} className="flex items-center text-sm font-semibold disabled:opacity-30">Próximo<ChevronRight size={18}/></button></div>
   </div></section></main>
  {started&&<section className="fixed inset-0 z-[120] flex min-h-[100dvh] flex-col overflow-hidden bg-[#061b14] text-[#fffaf0]"><img src="/brand/human-chakra-model.jpg" alt="Corpo em meditação" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-b from-[#03130d]/75 via-transparent to-[#03130d]/95"/><button onClick={()=>{stop();setStarted(false)}} className="absolute right-4 top-4 z-20 rounded-full bg-black/35 p-3"><X size={22}/></button><div className="relative z-10 flex flex-1 items-center justify-center"><Lights large/></div><div className="relative z-10 space-y-4 bg-gradient-to-t from-[#03130d] via-[#03130d]/95 to-transparent px-6 pb-6 pt-12 text-center"><p className="text-xs uppercase tracking-[.22em] text-[#ead28d]">Dia {day} · {item.title}</p><p className="font-display text-2xl">{playing?'Permaneça neste momento':'Meditação pausada'}</p><p className="mx-auto max-w-md leading-7">{reflection}</p><p className="text-xs text-[#b9cdbf]">Chakras em foco: {detail.chakras.join(' · ')}</p><div className="mx-auto max-w-md"><div className="h-2 overflow-hidden rounded-full bg-white/20"><div className="h-full bg-[#e5c568]" style={{width:`${progress}%`}}/></div><div className="mt-2 flex justify-between text-xs"><span>{fmt(elapsed)}</span><span>{fmt(total)}</span></div></div><div className="flex justify-center gap-3"><button onClick={rewind} className="flex items-center gap-2 rounded-full border border-white/30 px-4 py-4"><RotateCcw size={20}/>15s</button><button onClick={toggle} className="flex min-w-48 items-center justify-center gap-3 rounded-full bg-[#e5c568] px-6 py-4 font-bold text-[#173f35]">{playing?<Pause size={21}/>:<Play size={21}/>} {playing?'Pausar':'Continuar'}</button></div></div></section>}
 </div>;
}